using HappyWarehouse.Domain.Entities;
using HappyWarehouse.Infrastructure.Context;

namespace HappyWarehouse.Application.Features.CountryFeature.Seed;

public static class CountrySeeder
{
    public static async Task SeedCountriesAsync(ApplicationDbContext dbContext)
    {
        var countries = new List<Country>
        {
            new Country("Afghanistan", "Seeder"),
            new Country("Albania", "Seeder"),
            new Country("Algeria", "Seeder"),
            new Country("Andorra", "Seeder"),
            new Country("Angola", "Seeder"),
            new Country("Antigua and Barbuda", "Seeder"),
            new Country("Argentina", "Seeder"),
            new Country("Armenia", "Seeder"),
            new Country("Australia", "Seeder"),
            new Country("Austria", "Seeder"),
            new Country("Azerbaijan", "Seeder"),
            new Country("Bahamas", "Seeder"),
            new Country("Bahrain", "Seeder"),
            new Country("Bangladesh", "Seeder"),
            new Country("Barbados", "Seeder"),
            new Country("Belarus", "Seeder"),
            new Country("Belgium", "Seeder"),
            new Country("Belize", "Seeder"),
            new Country("Benin", "Seeder"),
            new Country("Bhutan", "Seeder"),
            new Country("Bolivia", "Seeder"),
            new Country("Bosnia and Herzegovina", "Seeder"),
            new Country("Botswana", "Seeder"),
            new Country("Brazil", "Seeder"),
            new Country("Brunei", "Seeder"),
            new Country("Bulgaria", "Seeder"),
            new Country("Burkina Faso", "Seeder"),
            new Country("Burundi", "Seeder"),
            new Country("Cabo Verde", "Seeder"),
            new Country("Cambodia", "Seeder"),
            new Country("Cameroon", "Seeder"),
            new Country("Canada", "Seeder"),
            new Country("Central African Republic", "Seeder"),
            new Country("Chad", "Seeder"),
            new Country("Chile", "Seeder"),
            new Country("China", "Seeder"),
            new Country("Colombia", "Seeder"),
            new Country("Comoros", "Seeder"),
            new Country("Congo (Congo-Brazzaville)", "Seeder"),
            new Country("Costa Rica", "Seeder"),
            new Country("Croatia", "Seeder"),
            new Country("Cuba", "Seeder"),
            new Country("Cyprus", "Seeder"),
            new Country("Czechia", "Seeder"),
            new Country("Democratic Republic of the Congo", "Seeder"),
            new Country("Denmark", "Seeder"),
            new Country("Djibouti", "Seeder"),
            new Country("Dominica", "Seeder"),
            new Country("Dominican Republic", "Seeder"),
            new Country("Ecuador", "Seeder"),
            new Country("Egypt", "Seeder"),
            new Country("El Salvador", "Seeder"),
            new Country("Equatorial Guinea", "Seeder"),
            new Country("Eritrea", "Seeder"),
            new Country("Estonia", "Seeder"),
            new Country("Eswatini", "Seeder"),
            new Country("Ethiopia", "Seeder"),
            new Country("Fiji", "Seeder"),
            new Country("Finland", "Seeder"),
            new Country("France", "Seeder"),
            new Country("Gabon", "Seeder"),
            new Country("Gambia", "Seeder"),
            new Country("Georgia", "Seeder"),
            new Country("Germany", "Seeder"),
            new Country("Ghana", "Seeder"),
            new Country("Greece", "Seeder"),
            new Country("Grenada", "Seeder"),
            new Country("Guatemala", "Seeder"),
            new Country("Guinea", "Seeder"),
            new Country("Guinea-Bissau", "Seeder"),
            new Country("Guyana", "Seeder"),
            new Country("Haiti", "Seeder"),
            new Country("Honduras", "Seeder"),
            new Country("Hungary", "Seeder"),
            new Country("Iceland", "Seeder"),
            new Country("India", "Seeder"),
            new Country("Indonesia", "Seeder"),
            new Country("Iran", "Seeder"),
            new Country("Iraq", "Seeder"),
            new Country("Ireland", "Seeder"),
            new Country("Spain", "Seeder"),
            new Country("Italy", "Seeder"),
            new Country("Jamaica", "Seeder"),
            new Country("Japan", "Seeder"),
            new Country("Jordan", "Seeder"),
            new Country("Kazakhstan", "Seeder"),
            new Country("Kenya", "Seeder"),
            new Country("Kiribati", "Seeder"),
            new Country("Kuwait", "Seeder"),
            new Country("Kyrgyzstan", "Seeder"),
            new Country("Laos", "Seeder"),
            new Country("Latvia", "Seeder"),
            new Country("Lebanon", "Seeder"),
            new Country("Lesotho", "Seeder"),
            new Country("Liberia", "Seeder"),
            new Country("Libya", "Seeder"),
            new Country("Liechtenstein", "Seeder"),
            new Country("Lithuania", "Seeder"),
            new Country("Luxembourg", "Seeder"),
            new Country("Madagascar", "Seeder"),
            new Country("Malawi", "Seeder"),
            new Country("Malaysia", "Seeder"),
            new Country("Maldives", "Seeder"),
            new Country("Mali", "Seeder"),
            new Country("Malta", "Seeder"),
            new Country("Marshall Islands", "Seeder")
        };
        
        await dbContext.Countries.AddRangeAsync(countries);
        await dbContext.SaveChangesAsync();
    }
}